version: "3"

services:
  api:
    build: .
    command: mix phx.server
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=4000
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - db

  db:
    image: postgres:9.6.3-alpine
    ports:
      - 5000:5432
    environment:
      - POSTGRES_PASSWORD=postgres
